I5T_shop/urls.py
from I5T_shop.views import HomeView
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('goods/', include('goods.urls')),
    path('order/', include('order.urls')),   
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

goods/urls.py
from goods.views import GoodsCreateView, GoodsDeleteView, GoodsUpdateView, ReviewDeleteView, goodsdetail, reviewcreate
from django.urls import path

app_name = 'goods'

urlpatterns = [
    # path('', GoodsListView.as_view(), name='index'),

    path('detail/<int:pk>', goodsdetail, name='detail'),
    path('add/', GoodsCreateView.as_view(), name="add"),
    path('<int:pk>/update/', GoodsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', GoodsDeleteView.as_view(), name="delete"),

    path('<int:pk>/reviewadd/', reviewcreate , name="review_add"), 
    path('<int:pk>/reviewdelete/', ReviewDeleteView.as_view(), name="review_delete"),
]

order/urls.py
from order.views import OrderCreateDoneView, order_create_approve, ordercreate
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('<int:pk>', ordercreate , name='order'),
    path('orderapprove/', order_create_approve , name="order_approve"), 
    path('done', OrderCreateDoneView.as_view(), name='order_done'),
]

goods/models.py
from goods.Validators import validate_score
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Goods(models.Model):
    # 상품명
    name = models.CharField(("NAME"), max_length=50)
    # 썸네일
    thumbnail = models.ImageField(("THUMBNAIL"), upload_to='photos/')
    # 상품설명
    goods_content = models.TextField(("CONTENT"))
    # 재고
    stock = models.IntegerField(("STOCK"))
    # 가격
    price = models.IntegerField("PRICE", default=None)
    # 관리자
    staff = models.ForeignKey(User, verbose_name="STAFF", on_delete=models.CASCADE, null=False, default=None)

    class Meta:
        pass

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('goods:detail', args=(self.id,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()
        
    def save(self, *args, **kwargs):
        # 필드 조정 필요시 작성
        super().save(*args, **kwargs)


class Review(models.Model):
    # 리뷰 쓴 사람
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    # 상품
    goods = models.ForeignKey("Goods", on_delete=models.CASCADE, blank=True, null=True)
    # 내용
    content = models.TextField(("content"))
    # 별점
    score = models.FloatField(("score"), default=None, null=True, validators=[validate_score])

    class Meta:
        pass

    def __str__(self):
        self.content

goods/forms.py
from goods.models import Review
from django import forms

class ReviewForm(forms.ModelForm):
  
    # create meta class
    class Meta:
        
        model = Review
        fields = [
            'content',
            'goods',
        ]
        labels = {
            'content' : '',
        }

        help_text ={
            'content' : '',
        }

        widgets = {
            'goods' : forms.HiddenInput(),
        }
    def save(self, **kwargs):
        review = super().save(commit=False)         # 부모메서드 호출 
        review.writer = kwargs.get('writer', None)
        review.save()

goods/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from accounts.views import StaffOnlyDeleteMixin, StaffOnlyMixin, writerOnlyMixin
from goods.forms import ReviewForm
from goods.models import Goods, Review
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic import DeleteView
from django.contrib.auth.decorators import login_required
# Create your views here.


# Goods

# PermissionRequiredMixin
class GoodsCreateView(LoginRequiredMixin,CreateView):
    model = Goods
    fields = ['name', 'thumbnail', 'goods_content', 'stock', 'price']
    template_name = 'goods/goods_create.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form): 
        form.instance.staff = self.request.user
        return super().form_valid(form)

class GoodsUpdateView(StaffOnlyMixin,UpdateView):
    model = Goods
    template_name = 'goods/goods_create.html'
    fields = ['name', 'thumbnail', 'goods_content', 'stock', 'price']
    success_url = reverse_lazy('home')


class GoodsDeleteView(StaffOnlyDeleteMixin,DeleteView):
    model = Goods
    success_url = reverse_lazy('home')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


# class GoodsDetailView(FormMixin, DetailView):
#     model = Goods
#     form_class = ReviewForm(initial={'goods':Goods})
    



def goodsdetail(req, pk):   
    context ={}
    goods = get_object_or_404(Goods, pk=pk)
    reviews = Review.objects.filter(goods=pk)
    form = ReviewForm(initial={'goods':goods})
    context = {'goods' : goods, 'reviews' : reviews, 'form':form}
    return render(req, 'goods/goods_detail.html', context=context)


# Review
@login_required
def reviewcreate(req, pk):
    if req.method == 'POST':
        form = ReviewForm(req.POST)
        if form.is_valid():
            form.save(writer = req.user)
            pk = int(pk)
        return redirect('goods:detail' , pk)
    return Http404


class ReviewDeleteView(writerOnlyMixin, DeleteView):
    model = Review
    success_url = reverse_lazy('home')
    # def delete(self, request, *args, **kwargs):
    #     """
    #     Call the delete() method on the fetched object and then redirect to the
    #     success URL.
    #     """
    #     self.object = self.get_object()
    #     success_url = self.get_success_url()
    #     self.object.delete()
    #     return HttpResponseRedirect(success_url)
    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

goods/templates/goods/goods_create.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block style %} <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}"> {% endblock %}


{% block content-header %}
<h1 class = 'col-sm-3 mx-auto'><i class="fas "></i></h1>
{% endblock %}


{% block content %}
<div class="row">
    <form action="." method="post" class="form col-sm-6 mx-auto" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-check">등록</i> 
        </button>
    </form>
</div>
{% endblock %}

{% block script %}
    <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}">
    </script>
    <script>
    $(function () { // Summernote 
        $('#id_goods_content').summernote({ height: 300 }) })
    </script>
{% endblock %}

goods/templates/goods/goods_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

<body onload="init();">
<script language="JavaScript">
var sell_price;
var amount;

function init () {
	sell_price = document.form.sell_price.value;
	amount = document.form.amount.value;
	document.form.sum.value = sell_price;
	change();
}

function add () {
	hm = document.form.amount;
	sum = document.form.sum;
	hm.value ++ ;

	sum.value = parseInt(hm.value) * sell_price;
}

function del () {
	hm = document.form.amount;
	sum = document.form.sum;
		if (hm.value > 1) {
			hm.value -- ;
			sum.value = parseInt(hm.value) * sell_price;
		}
}

function change () {
	hm = document.form.amount;
	sum = document.form.sum;

		if (hm.value < 0) {
			hm.value = 0;
		}
	sum.value = parseInt(hm.value) * sell_price;
}  
</script>

{% block content-header %}

{% endblock %}

{% block content %}

<div class="row">
    <div class="col">
        <img src='{{goods.thumbnail.url}}' width="600" height="600"/>
    </div>
    
    <div>
        <div class="col">
            <font size="6em">{{goods}}</p></font>  
        </div>
        <hr style="border: double 5px;">
        <div>
            <span style="color:gray;"><i class="fas fa-bell"></i><h4>
        <div>
            <span style="color:red;"> <font size="5em">{{goods.price}}원</font></span>
        </div>
        <hr>
        <div>
            <font size="4em" color="gray">색상: </font><font size="4em" color="black">블랙</font>
        </div>
        <hr>
        <div>
            <font size="5em">무료 배송</font>
        </div>
        <hr>
        <div>
            <form name="form" method="get">
            수량 : <input type=hidden name="sell_price" value="26930">
            <input type="text" name="amount" value="1" size="3" onchange="change();">
            <input type="button" value=" + " onclick="add();"><input type="button" value=" - " onclick="del();"><br>

            금액 : <input type="text" name="sum" size="11" readonly> 원
            </form>
        </div>
        <hr>
        <!-- 구매페이지 이동 경로 설정-->
        <div>
            <a class="btn btn-success btn-lg" href="{%url 'order:order' goods.id%}" role="button">바로 구매</a>
        </div>
        <hr>
    </div>
    
</div>




 
 <div>
   <div class="container">
        <h2><b>※ 필수 표기정보</b></h2>
        <table class="table table-bordered table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">품명 및 모델명</th>
                    <th scope="col">[로지텍] G102 2세대 LIGHTSYNC</th>
                    <th scope="col">KC 인증 필 유무</th>
                    <th scope="col">R-R-DZL-MU0054</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">정격전압, 소비전력</th>
                    <td>알 수 없음(업체미제공)</td>
                    <td>에너지소비효율등급</td>
                    <td>해당없음</td>
                </tr>
                <tr>
                    <th scope="row">출시년월</th>
                    <td>2020.07</td>
                    <td>제조자(수입자)</td>
                    <td>Logitech Technology Co.,Ltd. /</td>
                </tr>
                <tr>
                    <th scope="row">제조국</th>
                    <td>중국</td>
                    <td>크기</td>
                    <td>컨텐츠참조</td>
                </tr>
                <tr>
                    <th scope="row">무게</th>
                    <td>컨텐츠참조</td>
                    <td>주요사항</td>
                    <td>컨텐츠참조</td>
                </tr>
                <tr>
                    <th scope="row">품질보증기준</th>
                    <td>제품 이상 시 공정거래위원회 고시 소비자 분쟁해결기준에 의거 보상합니다.</td>
                    <td>A/S 책임자와 전화번호</td>
                    <td>1577-7011</td>
                </tr>
            </tbody>
        </table>

    </div>
    <div>
        <p style="text-align:center;">
        {{goods.goods_content | safe}}
        </p>
    </div>  
</div>
<div>
{% if user.is_staff %}
    <a class="btn btn-primary" href="{%url 'goods:update' goods.id%}" role="button">상품수정</a>
    <a class="btn btn-danger" href="{%url 'goods:delete' goods.id%}" role="button">상품삭제</a>
{% endif %}

</div>
<table class="table table-success">
    <thead>
        <tr>
            <th scope="col">상품 후기</th>
        </tr>
    </thead>

<div class="container">
    <table class="table table-hover">
    <thead>
    <tr>
        <th>작성자</th>
        <th>내용</th>
    </tr>
    </thead>
    <tbody>
    {% for review in reviews %}
    <tr>
        <td>{{review.writer}}</td>
        <td>{{review.content}}</td>
        {% if user.is_active %}
            <td><a class="btn btn-danger" href="{%url 'goods:review_delete' review.id%}" role="button">삭제</a></td>
        {% endif %}
        
    </tr>
    {% endfor %}
    {% comment %} <tr>
        <td>2</td>
        <td>안 좋아요 ^^</td>
        <td>아라</td>
        <td>2021.08.09</td>
        <td>3</td>
    </tr>
    <tr>
        <td>3</td>
        <td>@@@@@@♚멀티캠퍼스☆♚♚신청시$$전원 전용강좌☜☜100%증정※@@@@@@@</td>
        <td>선미</td>
        <td>2021.08.09</td>
        <td>1</td>
    </tr>
    <tr>
        <td>4</td>
        <td>여기 좀 이상한거 같애오...</td>
        <td>기선</td>
        <td>2021.08.09</td>
        <td>6</td>
    </tr>
    {% endcomment %}
     </tbody> 
    </table>
    <hr/> 
</div>
    <form action="{%url 'goods:review_add' goods.id%}" method="post" class="form col-sm-6 mx-auto" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-check">후기 작성</i> 
        </button>
    </form>

{% endblock %}