I5T_shop/urls.py
from I5T_shop.views import HomeView
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('goods/', include('goods.urls')),
    path('order/', include('order.urls')),   
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

goods/urls.py
from goods.views import GoodsCreateView, GoodsDeleteView, GoodsUpdateView, ReviewDeleteView, goodsdetail, reviewcreate
from django.urls import path

app_name = 'goods'

urlpatterns = [
    # path('', GoodsListView.as_view(), name='index'),

    path('detail/<int:pk>', goodsdetail, name='detail'),
    path('add/', GoodsCreateView.as_view(), name="add"),
    path('<int:pk>/update/', GoodsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', GoodsDeleteView.as_view(), name="delete"),

    path('<int:pk>/reviewadd/', reviewcreate , name="review_add"), 
    path('<int:pk>/reviewdelete/', ReviewDeleteView.as_view(), name="review_delete"),
]

order/urls.py
from order.views import OrderCreateDoneView, order_create_approve, ordercreate
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('<int:pk>', ordercreate , name='order'),
    path('orderapprove/', order_create_approve , name="order_approve"), 
    path('done', OrderCreateDoneView.as_view(), name='order_done'),
]

order/models.py
from goods.models import Goods
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Order(models.Model):
    # 구매자
    customer = models.ForeignKey(User, verbose_name=("customer"), on_delete=models.CASCADE, null=False, default=None)
    # 상품 id
    goods_id = models.ForeignKey(Goods, verbose_name=("goods"), on_delete=models.CASCADE, null=False, default=None)
    # 주소
    address = models.CharField(("ADDRESS"), max_length=50)
    # 수량
    quantity = models.IntegerField(("QUANTITY"))
    # 휴대전화
    sellphone = models.CharField(("phonenumber"), max_length=50,  null=False, default=None)
    customer_name = models.CharField(("customer_name"), max_length=50, null=False, default=None)
    
    class Meta:
        pass

    def __str__(self):
        pass

order/forms.py
from order.models import Order
from django import forms


class OrderForm(forms.ModelForm):

    class Meta:
        
        model = Order

        fields = [
            'customer_name',
            'address',
            'quantity',
            'goods_id',
            'sellphone',
        ]

        labels = {
            'customer_name' : '이름',
            "address" : '주소',
            'quantity' : '수량',
            'sellphone': '휴대전화',
        }

        help_text ={
            'customer_name' : '이름',
            "address" : '주소를 입력해 주세요',
            'quantity' : '수량을 입력해 주세요',
            'sellphone': '휴대전화번호를 입력해 주세요',
        }

        widgets = {
            'goods_id' : forms.HiddenInput(),
        }
    def save(self, **kwargs):
        order = super().save(commit=False)         # 부몽메서드 호출 
        order.customer = kwargs.get('customer', None)
        order.save()

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Permission
from django.http.response import Http404
from order.forms import OrderForm
from goods.models import Goods
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def ordercreate(req, pk):    
    context ={}
    goods = get_object_or_404(Goods, pk=pk)
    form = OrderForm(initial={'goods_id':goods})
    context = {'goods' : goods, 'form':form}
    return render(req, 'order/order_create.html', context=context)

@login_required
def order_create_approve(req):
    if req.method == 'POST':
        form = OrderForm(req.POST)
        if form.is_valid():
            form.save(customer = req.user)
        return redirect('order:order_done')
    return Http404()

class OrderCreateDoneView(TemplateView):
    template_name = 'order/order_done.html'

order/templates/order/order_create.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content-header %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock content-header %}

{% block content %}
<div>
    <div class="order_info">
        <div class="order_header">
            <h3 class="order_h3">주문/결제</h3>
        </div>
        <br>
        <div class="recipient_info">
            <h2 class="reci_h2">정보</h2>
            <form action="{%url 'order:order_approve' %}" method="post" class="form col-sm-6 mx-auto was-validated" >
                {% csrf_token %}
                {% bootstrap_form form %}
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" name="remember" required> 위 주문 내용을 확인 하였으며, 결제에 동의합니다.
                    <div class="valid-feedback">동의함</div>
                    <div class="invalid-feedback">계속하려면 동의하세요</div>
                </label>
            </div>
    
                <button type="submit" class="btn btn-primary">결제하기</button>
            </form>
    </div>
</div>


    <div>
        <h4>무통장입금(가상계좌)</h4>
        <ul>
            <li>
                <label>입금은행</label>
                <div>
                    <select>
                        <option>선택</option>
                        <option>농협은행</option>
                        <option>국민은행</option>
                        <option>신한은행</option>
                        <option>우리은행</option>
                        <option>하나은행</option>
                        <option>기업은행</option>
                    </select>
                </div>
            </li>
        </ul>
    </div>
</div>









{% endblock %}

order/templates/order/order_done.html
{% extends 'base.html' %}

{% block content-header %}
    <h1><i class="fas fa-user-plus"></i>주문 완료</h1>
{% endblock content-header %}

{% block content %}
    <div class="my-5 ml-5">
        <p>주문이 완료되었습니다.</p>
        <p class="font-italic"><a href="{% url 'home' %}">홈</a> </p>
    </div>
{% endblock content %}