I5T_shop/urls.py
from I5T_shop.views import HomeView
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('goods/', include('goods.urls')),
    path('order/', include('order.urls')),   
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from accounts.views import UserCreateDoneView, UserCreateView
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('register/done', UserCreateDoneView.as_view(), name='register_done'),
]

goods/urls.py
from goods.views import GoodsCreateView, GoodsDeleteView, GoodsUpdateView, ReviewDeleteView, goodsdetail, reviewcreate
from django.urls import path

app_name = 'goods'

urlpatterns = [
    # path('', GoodsListView.as_view(), name='index'),

    path('detail/<int:pk>', goodsdetail, name='detail'),
    path('add/', GoodsCreateView.as_view(), name="add"),
    path('<int:pk>/update/', GoodsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', GoodsDeleteView.as_view(), name="delete"),

    path('<int:pk>/reviewadd/', reviewcreate , name="review_add"), 
    path('<int:pk>/reviewdelete/', ReviewDeleteView.as_view(), name="review_delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>I5T shop</title>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>

    <!-- 스타일 -->

    
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=f
    allback">
    <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
    <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">



    {% block style %}{% endblock %}
</head>

<body class="hold-transition skin-blue-light layout-top-nav">
<div class="wrapper">
    {% include "menu.html" %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
            {% block content-header %}{% endblock %}
            </div>
        </div>
 
        <div class="content">
            <div class="container-fluid">
            {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    {% include "footer.html" %}
    <!-- 기본 스크립트 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>

    {% block script %}{% endblock %}
    
</body>

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        I5T 
    </div>
    <!-- Default to the left -->
    <strong>
        Copyright &copy; 2021 <a href="{% url 'home' %}">I5T shop</a>. 
    </strong> 
    All rights reserved.
</footer>

templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}
    <!-- Bootstrap cdn 설정 -->
    <div id="demo" class="carousel slide" data-ride="carousel" style="max-width:72%; width:auto; margin: 100px;">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="/static/images/banner.png" alt='1'style="width:100%">
        <div class="carousel-caption" style="color:black;">
            <h3 style=" Font-size:50px;">
                <strong></strong>
            </h3>
            <p></p>
        </div>
    </div>

  {% for goods in object_list %}
    <div class="carousel-item">
        <img src="{{goods.thumbnail.url}}" alt="{{goods.name}}" style="width:100%">
        <div class="carousel-caption" style="color:black;">
            <h3 style=" Font-size:50px;">
                <strong>{{goods}}</strong>
            </h3>
            <p>{{goods.price}}원</p>
        </div>
    </div>
  {% endfor %}
    {% comment %}

    <div class="carousel-item">
        <img src="/static/images/009.jpg" alt="003" style="width:100%">
        <div class="carousel-caption" style="color:black;">
            <h3 style=" Font-size:50px;">
                <strong>3rd</strong>
            </h3>
            <p>{{goods}}</p>
        </div>
    </div> {% endcomment %}

  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>



<div class="flex-container" style="display: flex; flex-wrap: wrap;">
   
       
        {% for goods in object_list %}
    <div class="main_goods_image" style="background-color:#f1f1f1; max-width:25%; margin: 10px; text-align: center;">
        <div class="img_info_1">
            <a href="{%url 'goods:detail' goods.id%}" class="img_link">
                <img class="goods_img" src="{{ goods.thumbnail.url }}" style="max-width:100%; height:auto;" alt="1st_goods image" />
            </a>
        </div>  

        <div class="goods_name" style="line-height:40px;">
            <a href="{%url 'goods:detail' goods.id%}" class="name_link" style="font-size:20px;">
                <strong>
                    {{goods}}
                </strong>
            </a>
            <p style="line-height:10px;">
               {{goods.price}} 원
            </p>
        </div>
    </div>
        {% endfor %}
</div>
  {% if user.is_staff %}
             <div class="text-right mr-3">
                <a href="{%url 'goods:add' %}" class="btn btn-primary btn-sm"><i class="fas fa-pencil-alt"></i>상품등록</a>
            </div>
    {% endif %}
    <br>
{% endblock %}

templates/menu.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        {% comment %} <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul> {% endcomment %}
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto mx-right-" href="{%url 'home' %}">
            <img src="/static/images/logo.png" width="125" height="40">
        </a>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if user.is_active %}
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'password_change' %}">
                    <i class="fas fa-user"></i> {{user.username}}</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fas fa-sign-out-alt"></i> 로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item d-none d-sm-inline-block" style="display:inline-block">
                <a class="nav-link" href="{% url 'login' %}">
                    <i class="fas fa-sign-in-alt"></i> 로그인</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block" style="display:inline-block">
                <a class="nav-link" href="{% url 'accounts:register' %}">
                    <i class="fas fa-user-plus"></i> 회원가입</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>